#Generate plot of aquaculture cycle over two years to display in model summary figure
source('Prawn_aquaculture/prawn_aquaculture_mod.R')
source('Prawn_aquaculture/macrobrachium_aquaculture_data.R')
require(tidyverse)

#Simulation for eumetric curve for M. volenhovenii #####
#Starting length of 32 mm corresponds to juveniles of ~0.45 grams
opt.df = expand.grid(L_nought = 32, P_nought = seq(100, 10000, 100)) 
  opt.df$h.t = 0
  opt.df$h.bm = 0
  opt.df$h.frac = 0
  opt.df$m.bm = 0
  opt.df$p.bm = 0
  opt.df$p.surv = 0
  opt.df$Revenue = 0
  opt.df$Profit = 0
  opt.df$ROI = 0

par.aqua['k'] = k.vol       # Growth rate (mm/day), from Nwosu & Wolfi 2006 (M. vollenhovenii)

  for(k in 1:nrow(opt.df)){
    start = c(P = opt.df[k,2], L = opt.df[k,1])
    market_frac = predict(eta.lm, newdata = data.frame(dens = start["P"]/area))

  #Run model with above starting conditions  
    op = as.data.frame(ode(start,t.p,prawn_biomass,par.aqua))
    
  #Estimate additional values for simulation  
    op$B = par.aqua['a.p']*op$L^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    op$Bt = op$P*op$B #Total biomass in grams of prawn population
    op$harvest_mass = op$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    op$revenue = (op$harvest_mass/1000)*p    #revenue generated by harvest
    op$profit = op$revenue*exp(-delta*op$time) - cost*(start["P"])   #profit generated by harvest
    op$roi = op$profit / (cost*(start["P"]))
    
  #Store parameters of optimal management  
    max_profit = max(op$profit)
    
    opt.df[k,3] = op$time[op$profit==max_profit]  # harvest time
    opt.df[k,4] = op$Bt[op$profit==max_profit]    # Total prawn biomass
    opt.df[k,5] = market_frac # Fraction of harvest that's marketable as function of stocking density
    opt.df[k,6] = opt.df[k,4] * opt.df[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df[k,7] = op$B[op$profit==max_profit]     # Prawn size at harvest
    opt.df[k,8] = op$P[op$profit==max_profit] / start["P"]   # Prawn % survival at harvest
    opt.df[k,9] = op$revenue[op$profit==max_profit]    # Raw revenue generated
    opt.df[k,10] = max_profit  #Net profit
    opt.df[k,11] = op$roi[op$profit==max_profit] # ROI  
    
  }

opt.df$p.t = opt.df$P_nought * opt.df$p.surv     #number of prawns alive at harvest
opt.df$Species = "M. volenhovenii"
  opt.df.criteria = subset(opt.df, p.bm >=30 & h.t <= 365)
  opt.vol = opt.df[which(opt.df$Profit == max(opt.df$Profit)),]
  opt.vol$bm0 = par.aqua['a.p']*opt.vol$L_nought^par.aqua['b.p'] * opt.vol$P_nought

#Simulation for eumetric curve for M. rosenbergii #####
opt.df.ros = opt.df
  opt.df.ros$h.t = 0
  opt.df.ros$h.bm = 0
  opt.df.ros$h.frac = 0
  opt.df.ros$m.bm = 0
  opt.df.ros$p.bm = 0
  opt.df.ros$p.surv = 0
  opt.df.ros$Revenue = 0
  opt.df.ros$Profit = 0
  opt.df.ros$ROI = 0
  
  par.aqua['k'] = k.ros    # alternate value for M. rosenbergii, from Sampaio & Valenti 1996: 0.0104333333
  
  for(k in 1:nrow(opt.df.ros)){
    start = c(P = opt.df.ros[k,2], L = opt.df.ros[k,1])
    market_frac = predict(eta.lm, newdata = data.frame(dens = start["P"]/area))

  #Run model with above starting conditions  
    op = as.data.frame(ode(start,t.p,prawn_biomass,par.aqua))
    
  #Estimate additional values for simulation  
    op$B = par.aqua['a.p']*op$L^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    op$Bt = op$P*op$B #Total biomass in grams of prawn population
    op$harvest_mass = op$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    op$revenue = (op$harvest_mass/1000)*p    #revenue generated by harvest
    op$profit = op$revenue*exp(-delta*op$time) - cost*(start["P"])   #profit generated by harvest
    op$roi = op$profit / (cost*(start["P"]))
    
  #Store parameters of optimal management  
    max_profit = max(op$profit)
    
    opt.df.ros[k,3] = op$time[op$profit==max_profit]  # harvest time
    opt.df.ros[k,4] = op$Bt[op$profit==max_profit]    # Total prawn biomass
    opt.df.ros[k,5] = market_frac # Fraction of harvest that's marketable as function of stocking density
    opt.df.ros[k,6] = opt.df.ros[k,4] * opt.df.ros[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df.ros[k,7] = op$B[op$profit==max_profit]     # Prawn size at harvest
    opt.df.ros[k,8] = op$P[op$profit==max_profit] / start["P"]   # Prawn % survival at harvest
    opt.df.ros[k,9] = op$revenue[op$profit==max_profit]    # Raw revenue generated
    opt.df.ros[k,10] = max_profit  #Net profit
    opt.df.ros[k,11] = op$roi[op$profit==max_profit] # ROI  
    
  }
 
opt.df.ros$p.t = opt.df.ros$P_nought * opt.df.ros$p.surv     #number of prawns alive at harvest
opt.df.ros$Species = "M. rosenbergii"
  opt.df.ros.criteria = subset(opt.df.ros, p.bm >=30 & h.t <= 365)
  opt.ros = opt.df.ros[which(opt.df.ros$Profit == max(opt.df.ros$Profit)),]
  opt.ros$bm0 = par.aqua['a.p']*opt.ros$L_nought^par.aqua['b.p'] * opt.ros$P_nought

    
#Simulate an aquaculture cycle based on profit-optimized stocking density for each species above ###########
t.p = c(0:(365*2))
    
#run model through 2 years for M. volenhovenii ######
par.aqua['k'] = k.vol  # alternate value for M. volenhovenii
nstart.p.vol = c(P = opt.vol$P_nought, L = opt.vol$L_nought)   #optimal starting conditions for M. volenhovenii as estimated above
op.vol = as.data.frame(ode(nstart.p.vol,t.p,prawn_biomass,par.aqua))

#post-process to estimate additional parameters
# 0) prawn density rather than raw prawn numbers
  op.vol$P.dens = op.vol$P / area
# 1) mean prawn biomass (allometric function)
  op.vol$B = par.aqua['a.p']*op.vol$L^par.aqua['b.p']
# 2) total prawn biomass (mean biomass * number of prawns)  
  op.vol$Bt = op.vol$B*op.vol$P / 1000
# 2.5) marketable prawns at harvest
  eta.vol = predict(eta.lm, newdata = data.frame(dens = nstart.p.vol["P"]/area)) # Fraction of harvest that's marketable as function of stocking density
# 2.6) marketable biomass 
  op.vol$marketable_mass = eta.vol*p*op.vol$Bt
# 3) profit (in terms of revenue (discounted by time since stocking) minus stocking costs )  
  op.vol$profit = eta.vol*p*op.vol$Bt*exp(-delta*(op.vol$t)) - cost*(nstart.p.vol["P"])
# 4) starting total biomass
  start.mass.kg.vol = op.vol$Bt[op.vol$time==0]
# 5) harvest mass in kg (harvest assumed to occur when profit is maximized)   
  harvest.mass.kg.vol = eta.vol*op.vol$Bt[op.vol$profit==max(op.vol$profit)]
# 6) average mass of prawns at harvest  
  harvest.size.vol = op.vol$B[op.vol$profit==max(op.vol$profit)]
# 6.5) average length of prawns at harvest  
  harvest.length.vol = op.vol$L[op.vol$profit==max(op.vol$profit)]
# 7) time of harvest (when biomass is maximized)
  harvest.time.vol = op.vol$time[op.vol$profit==max(op.vol$profit)]
# 8) time in months
  op.vol$time.mo = op.vol$time / 30
# 9) species
  op.vol$Species = 'M. volenhovenii'

#run model through 2 years for M. rosenbergii ######
par.aqua['k'] = k.ros  # alternate value for M. rosenbergii, from Sampaio & Valenti 1996
nstart.p.ros = c(P = opt.ros$P_nought, L = opt.ros$L_nought)   #optimal starting conditions for M. rosenbergii as estimated above
op.ros = as.data.frame(ode(nstart.p.ros,t.p,prawn_biomass,par.aqua))

#post-process to estimate additional parameters
# 0) prawn density rather than raw prawn numbers
  op.ros$P.dens = op.ros$P / area
# 1) mean prawn biomass (allometric function)
  op.ros$B = par.aqua['a.p']*op.ros$L^par.aqua['b.p']
# 2) total prawn biomass (mean biomass * number of prawns)  
  op.ros$Bt = op.ros$B*op.ros$P / 1000
# 2.5) marketable prawns at harvest
  eta.ros = predict(eta.lm, newdata = data.frame(dens = nstart.p.ros["P"]/area)) # Fraction of harvest that's marketable as function of stocking density
# 2.6) marketable biomass 
  op.ros$marketable_mass = eta.ros*p*op.ros$Bt
# 3) profit (in terms of revenue (discounted by time since stocking) minus stocking costs )  
  op.ros$profit = eta.ros*p*op.ros$Bt*exp(-delta*(op.ros$t)) - cost*(nstart.p.ros["P"])
# 4) starting total biomass
  start.mass.kg.ros = op.ros$Bt[op.ros$time==0]
# 5) harvest mass in kg (harvest assumed to occur when profit is maximized)   
  harvest.mass.kg.ros = eta.ros*op.ros$Bt[op.ros$profit==max(op.ros$profit)]
# 6) average mass of prawns at harvest  
  harvest.size.ros = op.ros$B[op.ros$profit==max(op.ros$profit)]
# 6.5) average length of prawns at harvest  
  harvest.length.ros = op.ros$L[op.ros$profit==max(op.ros$profit)]
# 7) time of harvest (when biomass is maximized)
  harvest.time.ros = op.ros$time[op.ros$profit==max(op.ros$profit)]
# 8) time in months
  op.ros$time.mo = op.ros$time / 30
# 9) species
  op.ros$Species = 'M. rosenbergii'
  
#Simulations with volenhovenii when restricting harvesting to 8 months ########## 
opt.df8mos = opt.df 
  opt.df8mos$h.t = 8*30
  opt.df8mos$h.bm = 0
  opt.df8mos$h.frac = 0
  opt.df8mos$m.bm = 0
  opt.df8mos$p.bm = 0
  opt.df8mos$p.surv = 0
  opt.df8mos$Revenue = 0
  opt.df8mos$Profit = 0
  opt.df8mos$ROI = 0

par.aqua['k'] = k.vol       # Growth rate (mm/day), from Nwosu & Wolfi 2006 (M. vollenhovenii)

  for(k in 1:nrow(opt.df8mos)){
    start = c(P = opt.df8mos[k,2], L = opt.df8mos[k,1])

    op = as.data.frame(ode(start,c(0:365),prawn_biomass,par.aqua))
    op$B = par.aqua['a.p']*op$L^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    
    opt.df8mos[k,3] = 240  # harvest time fixed at 8 months
    opt.df8mos[k,4] = op$B[op$time == 240]*op$P[op$time == 240]                      # Total prawn biomass
    opt.df8mos[k,5] = predict(eta.lm, newdata = data.frame(dens = opt.df8mos[k,2]/area)) # Fraction of harvest that's marketable as function of stocking density
    opt.df8mos[k,6] = opt.df8mos[k,4] * opt.df8mos[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df8mos[k,7] = op$B[op$time == 240]     # Prawn size at harvest
    opt.df8mos[k,8] = op$P[op$time == 240] / opt.df8mos[k,2]   # Prawn % survival at harvest
    opt.df8mos[k,9] = p*(opt.df8mos[k,4]/1000)*opt.df8mos[k,5]    # Raw Profit
    opt.df8mos[k,10] = p*(opt.df8mos[k,4]/1000)*opt.df8mos[k,5]*exp(-delta*opt.df8mos[k,3]) - cost*(start["P"])  #Net profit
    opt.df8mos[k,11] = (p*(opt.df8mos[k,4]/1000)*opt.df8mos[k,5]*exp(-delta*opt.df8mos[k,3]) - cost*(start["P"])) / (cost*(start["P"])) # ROI  
    
  }

opt.df8mos$p.t = opt.df8mos$P_nought * opt.df8mos$p.surv     #number of prawns alive at harvest
opt.df8mos$Species = "M. volenhovenii"
  opt.vol8mos = opt.df8mos[which(opt.df8mos$Profit == max(opt.df8mos$Profit)),]

  
#Simulations with rosenbergii when restricting harvesting to 8 months ########## 
opt.df.ros8mos = opt.df
  opt.df.ros8mos$h.t = 8*30
  opt.df.ros8mos$h.bm = 0
  opt.df.ros8mos$h.frac = 0
  opt.df.ros8mos$m.bm = 0
  opt.df.ros8mos$p.bm = 0
  opt.df.ros8mos$p.surv = 0
  opt.df.ros8mos$Revenue = 0
  opt.df.ros8mos$Profit = 0
  opt.df.ros8mos$ROI = 0

  par.aqua['k'] = k.ros    # alternate value for M. rosenbergii, from Sampaio & Valenti 1996: 0.0104333333

  for(k in 1:nrow(opt.df.ros8mos)){
    start = c(P = opt.df.ros8mos[k,2], L = opt.df.ros8mos[k,1])

    op = as.data.frame(ode(start,c(0:365),prawn_biomass,par.aqua))
    op$B = par.aqua['a.p']*op$L^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    
    opt.df.ros8mos[k,3] = 240  # harvest time fixed at 8 months
    opt.df.ros8mos[k,4] = op$B[op$time == 240]*op$P[op$time == 240]                      # Total prawn biomass
    opt.df.ros8mos[k,5] = predict(eta.lm, newdata = data.frame(dens = opt.df.ros8mos[k,2]/area)) # Fraction of harvest that's marketable as function of stocking density
    opt.df.ros8mos[k,6] = opt.df.ros8mos[k,4] * opt.df.ros8mos[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df.ros8mos[k,7] = op$B[op$time == 240]     # Prawn size at harvest
    opt.df.ros8mos[k,8] = op$P[op$time == 240] / opt.df.ros8mos[k,2]   # Prawn % survival at harvest
    opt.df.ros8mos[k,9] = p*(opt.df.ros8mos[k,4]/1000)*opt.df.ros8mos[k,5]    # Raw Profit
    opt.df.ros8mos[k,10] = p*(opt.df.ros8mos[k,4]/1000)*opt.df.ros8mos[k,5]*exp(-delta*opt.df.ros8mos[k,3]) - cost*(start["P"])  #Net profit
    opt.df.ros8mos[k,11] = (p*(opt.df.ros8mos[k,4]/1000)*opt.df.ros8mos[k,5]*exp(-delta*opt.df.ros8mos[k,3]) - cost*(start["P"])) / (cost*(start["P"])) # ROI  
    
  }

opt.df.ros8mos$p.t = opt.df.ros8mos$P_nought * opt.df.ros8mos$p.surv     #number of prawns alive at harvest
opt.df.ros8mos$Species = "M. rosenbergii"
  opt.ros8mos = opt.df.ros8mos[which(opt.df.ros8mos$Profit == max(opt.df.ros8mos$Profit)),]
  
#Simulations for supplementary figure showing aquaculture dynamics through time across different stocking densities ###########
sim_aqua <- function(P0, species = "M. volenhovenii"){
  
#Set starting parameters based on stocking density  
  sim_start = c(P = P0, L = opt.df[k,1])

#Get marketable fraction of harvest as function of stocking density    
  market_frac = predict(eta.lm, newdata = data.frame(dens = P0/area))
  
#Set growth rate based on species  
  if(species == "M. volenhovenii"){
    par.aqua['k'] = k.vol
  } else {
    par.aqua['k'] = k.ros
  }
  
#Simulate for two years  
  sim_df <- as.data.frame(ode(sim_start,t.p,prawn_biomass,par.aqua))
  
  #Estimate additional values for simulation  
    sim_df$P_dens = sim_df$P / area
    sim_df$B = par.aqua['a.p']*sim_df$L^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    sim_df$Bt = sim_df$P*sim_df$B /1000 #Total biomass in kilograms of prawn population
    sim_df$harvest_mass = sim_df$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    sim_df$revenue = (sim_df$harvest_mass)*p    #revenue generated by harvest
    sim_df$profit = sim_df$revenue*exp(-delta*sim_df$time) - cost*(sim_start["P"])   #profit generated by harvest
    sim_df$roi = sim_df$profit / (cost*(sim_start["P"]))
    sim_df$species = species
    sim_df$P0 = P0 / area
    
  return(as.matrix(sim_df))  

}
  
test_p0s <- seq(1000, 8000, 1000)  

aqua_sims_vol <- do.call(rbind, lapply(test_p0s, sim_aqua))
aqua_sims_ros <- do.call(rbind, lapply(test_p0s, sim_aqua, species = "M. rosenbergii"))

aqua_sims = as.data.frame(rbind(aqua_sims_vol, aqua_sims_ros)) %>% 
  gather(key = "Variable", value = "Value", P:roi)

save.image(file = "Prawn_aquaculture/aquaculture_sims.RData")  
