#Investigate influence of doubled mortality rate on prawn aquaculture model results and reproduce Figs 2-5

rm(list = ls())

source('Prawn_aquaculture/prawn_aquaculture_mod.R')
source('Prawn_aquaculture/macrobrachium_aquaculture_data.R')
load("Prawn_aquaculture/aquaculture_sims.RData")

require(tidyverse)

par.aqua['muP'] <- par.aqua['muP']*4

#Simulation for eumetric curve for M. volenhovenii #####
#Starting length of 32 mm corresponds to juveniles of ~0.45 grams
opt.df = expand.grid(L_nought = 32, P_nought = seq(100, 10000, 100)) 
  opt.df$h.t = 0
  opt.df$h.bm = 0
  opt.df$h.frac = 0
  opt.df$m.bm = 0
  opt.df$p.bm = 0
  opt.df$p.surv = 0
  opt.df$Revenue = 0
  opt.df$Profit = 0
  opt.df$ROI = 0

par.aqua['k'] = 0.00339726       # Growth rate (mm/day), from Nwosu & Wolfi 2006 (M. vollenhovenii)

  for(k in 1:nrow(opt.df)){
    start = c(P = opt.df[k,2], L = opt.df[k,1])
    market_frac = predict(eta.lm, newdata = data.frame(dens = start["P"]/area))

  #Run model with above starting conditions  
    op = as.data.frame(ode(start,t.p,prawn_biomass,par.aqua))
    
  #Estimate additional values for simulation  
    op$B = (par.aqua['a.p']/10)*(op$L/10)^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    op$Bt = op$P*op$B #Total biomass in grams of prawn population
    op$harvest_mass = op$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    op$revenue = (op$harvest_mass/1000)*p    #revenue generated by harvest
    op$profit = op$revenue*exp(-delta*op$time) - cost*(start["P"])   #profit generated by harvest
    op$roi = op$profit / (cost*(start["P"]))
    
  #Store parameters of optimal management  
    max_profit = max(op$profit)
    
    opt.df[k,3] = op$time[op$profit==max_profit]  # harvest time
    opt.df[k,4] = op$Bt[op$profit==max_profit]    # Total prawn biomass
    opt.df[k,5] = market_frac # Fraction of harvest that's marketable as function of stocking density
    opt.df[k,6] = opt.df[k,4] * opt.df[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df[k,7] = op$B[op$profit==max_profit]     # Prawn size at harvest
    opt.df[k,8] = op$P[op$profit==max_profit] / start["P"]   # Prawn % survival at harvest
    opt.df[k,9] = op$revenue[op$profit==max_profit]    # Raw revenue generated
    opt.df[k,10] = max_profit  #Net profit
    opt.df[k,11] = op$roi[op$profit==max_profit] # ROI  
    
  }

opt.df$p.t = opt.df$P_nought * opt.df$p.surv     #number of prawns alive at harvest
opt.df$Species = "M. volenhovenii"
  opt.df.criteria = subset(opt.df, p.bm >=30 & h.t <= 365)
  opt.vol = opt.df[which(opt.df$Profit == max(opt.df$Profit)),]
  opt.vol$bm0 = (par.aqua['a.p']/10)*(opt.vol$L_nought/10)^par.aqua['b.p'] * opt.vol$P_nought

#Simulation for eumetric curve for M. rosenbergii #####
opt.df.ros = opt.df
  opt.df.ros$h.t = 0
  opt.df.ros$h.bm = 0
  opt.df.ros$h.frac = 0
  opt.df.ros$m.bm = 0
  opt.df.ros$p.bm = 0
  opt.df.ros$p.surv = 0
  opt.df.ros$Revenue = 0
  opt.df.ros$Profit = 0
  opt.df.ros$ROI = 0
  
  par.aqua['k'] = 0.0104333333    # alternate value for M. rosenbergii, from Sampaio & Valenti 1996: 0.0104333333
  
  for(k in 1:nrow(opt.df.ros)){
    start = c(P = opt.df.ros[k,2], L = opt.df.ros[k,1])
    market_frac = predict(eta.lm, newdata = data.frame(dens = start["P"]/area))

  #Run model with above starting conditions  
    op = as.data.frame(ode(start,t.p,prawn_biomass,par.aqua))
    
  #Estimate additional values for simulation  
    op$B = (par.aqua['a.p']/10)*(op$L/10)^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    op$Bt = op$P*op$B #Total biomass in grams of prawn population
    op$harvest_mass = op$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    op$revenue = (op$harvest_mass/1000)*p    #revenue generated by harvest
    op$profit = op$revenue*exp(-delta*op$time) - cost*(start["P"])   #profit generated by harvest
    op$roi = op$profit / (cost*(start["P"]))
    
  #Store parameters of optimal management  
    max_profit = max(op$profit)
    
    opt.df.ros[k,3] = op$time[op$profit==max_profit]  # harvest time
    opt.df.ros[k,4] = op$Bt[op$profit==max_profit]    # Total prawn biomass
    opt.df.ros[k,5] = market_frac # Fraction of harvest that's marketable as function of stocking density
    opt.df.ros[k,6] = opt.df.ros[k,4] * opt.df.ros[k,5]           # Marketable harvest (total biomass times fraction marketable size)
    opt.df.ros[k,7] = op$B[op$profit==max_profit]     # Prawn size at harvest
    opt.df.ros[k,8] = op$P[op$profit==max_profit] / start["P"]   # Prawn % survival at harvest
    opt.df.ros[k,9] = op$revenue[op$profit==max_profit]    # Raw revenue generated
    opt.df.ros[k,10] = max_profit  #Net profit
    opt.df.ros[k,11] = op$roi[op$profit==max_profit] # ROI  
    
  }
 
opt.df.ros$p.t = opt.df.ros$P_nought * opt.df.ros$p.surv     #number of prawns alive at harvest
opt.df.ros$Species = "M. rosenbergii"
  opt.df.ros.criteria = subset(opt.df.ros, p.bm >=30 & h.t <= 365)
  opt.ros = opt.df.ros[which(opt.df.ros$Profit == max(opt.df.ros$Profit)),]
  opt.ros$bm0 = (par.aqua['a.p']/10)*(opt.ros$L_nought/10)^par.aqua['b.p'] * opt.ros$P_nought

    


#run model through 2 years for M. volenhovenii ######
par.aqua['k'] = 0.00339726  # alternate value for M. volenhovenii
nstart.p.vol = c(P = opt.vol$P_nought, L = opt.vol$L_nought)   #optimal starting conditions for M. volenhovenii as estimated above
op.vol = as.data.frame(ode(nstart.p.vol,t.p,prawn_biomass,par.aqua))

#post-process to estimate additional parameters
# 0) prawn density rather than raw prawn numbers
  op.vol$P.dens = op.vol$P / area
# 1) mean prawn biomass (allometric function)
  op.vol$B = (par.aqua['a.p']/10)*(op.vol$L/10)^par.aqua['b.p']
# 2) total prawn biomass (mean biomass * number of prawns)  
  op.vol$Bt = op.vol$B*op.vol$P / 1000
# 2.5) marketable prawns at harvest
  eta.vol = predict(eta.lm, newdata = data.frame(dens = nstart.p.vol["P"]/area)) # Fraction of harvest that's marketable as function of stocking density
# 3) profit (in terms of revenue (discounted by time since stocking) minus stocking costs )  
  op.vol$profit = eta.vol*p*op.vol$Bt*exp(-delta*(op.vol$t)) - cost*(nstart.p.vol["P"])
# 4) starting total biomass
  start.mass.kg.vol = op.vol$Bt[op.vol$time==0]
# 5) harvest mass in kg (harvest assumed to occur when profit is maximized)   
  harvest.mass.kg.vol = eta.vol*op.vol$Bt[op.vol$profit==max(op.vol$profit)]
# 6) average mass of prawns at harvest  
  harvest.size.vol = op.vol$B[op.vol$profit==max(op.vol$profit)]
# 6.5) average length of prawns at harvest  
  harvest.length.vol = op.vol$L[op.vol$profit==max(op.vol$profit)]
# 7) time of harvest (when biomass is maximized)
  harvest.time.vol = op.vol$time[op.vol$profit==max(op.vol$profit)]
# 8) time in months
  op.vol$time.mo = op.vol$time / 30
# 9) species
  op.vol$Species = 'M. volenhovenii'

#run model through 2 years for M. rosenbergii ######
par.aqua['k'] = 0.0104333333  # alternate value for M. rosenbergii, from Sampaio & Valenti 1996
nstart.p.ros = c(P = opt.ros$P_nought, L = opt.ros$L_nought)   #optimal starting conditions for M. rosenbergii as estimated above
op.ros = as.data.frame(ode(nstart.p.ros,t.p,prawn_biomass,par.aqua))

#post-process to estimate additional parameters
# 0) prawn density rather than raw prawn numbers
  op.ros$P.dens = op.ros$P / area
# 1) mean prawn biomass (allometric function)
  op.ros$B = (par.aqua['a.p']/10)*(op.ros$L/10)^par.aqua['b.p']
# 2) total prawn biomass (mean biomass * number of prawns)  
  op.ros$Bt = op.ros$B*op.ros$P / 1000
# 2.5) marketable prawns at harvest
  eta.ros = predict(eta.lm, newdata = data.frame(dens = nstart.p.ros["P"]/area)) # Fraction of harvest that's marketable as function of stocking density
# 3) profit (in terms of revenue (discounted by time since stocking) minus stocking costs )  
  op.ros$profit = eta.ros*p*op.ros$Bt*exp(-delta*(op.ros$t)) - cost*(nstart.p.ros["P"])
# 4) starting total biomass
  start.mass.kg.ros = op.ros$Bt[op.ros$time==0]
# 5) harvest mass in kg (harvest assumed to occur when profit is maximized)   
  harvest.mass.kg.ros = eta.ros*op.ros$Bt[op.ros$profit==max(op.ros$profit)]
# 6) average mass of prawns at harvest  
  harvest.size.ros = op.ros$B[op.ros$profit==max(op.ros$profit)]
# 6.5) average length of prawns at harvest  
  harvest.length.ros = op.ros$L[op.ros$profit==max(op.ros$profit)]
# 7) time of harvest (when biomass is maximized)
  harvest.time.ros = op.ros$time[op.ros$profit==max(op.ros$profit)]
# 8) time in months
  op.ros$time.mo = op.ros$time / 30
# 9) species
  op.ros$Species = 'M. rosenbergii'
  
  
  
#Simulations for figure showing aquaculture dynamics through time across different stocking densities ###########
sim_aqua <- function(P0, species = "M. volenhovenii"){
  
#Set starting parameters based on stocking density  
  sim_start = c(P = P0, L = opt.df[k,1])

#Get marketable fraction of harvest as function of stocking density    
  market_frac = predict(eta.lm, newdata = data.frame(dens = P0/area))
  
#Set growth rate based on species  
  if(species == "M. volenhovenii"){
    par.aqua['k'] = 0.00339726
  } else {
    par.aqua['k'] = 0.0104333333
  }
  
#Simulate for two years  
  sim_df <- as.data.frame(ode(sim_start,t.p,prawn_biomass,par.aqua))
  
  #Estimate additional values for simulation  
    sim_df$P_dens = sim_df$P / area
    sim_df$B = (par.aqua['a.p']/10)*(sim_df$L/10)^par.aqua['b.p']     # Mean prawn biomass, transformed from length in mm
    sim_df$Bt = sim_df$P*sim_df$B /1000 #Total biomass in kilograms of prawn population
    sim_df$harvest_mass = sim_df$Bt * market_frac   #harvest biomass estimated as total biomass times marketable fraction
    sim_df$revenue = (sim_df$harvest_mass)*p    #revenue generated by harvest
    sim_df$profit = sim_df$revenue*exp(-delta*sim_df$time) - cost*(sim_start["P"])   #profit generated by harvest
    sim_df$roi = sim_df$profit / (cost*(sim_start["P"]))
    sim_df$species = species
    sim_df$P0 = P0 / area
    
  return(as.matrix(sim_df))  

}
  
test_p0s <- seq(1000, 8000, 1000)  

aqua_sims_vol <- do.call(rbind, lapply(test_p0s, sim_aqua))
aqua_sims_ros <- do.call(rbind, lapply(test_p0s, sim_aqua, species = "M. rosenbergii"))

aqua_sims = as.data.frame(rbind(aqua_sims_vol, aqua_sims_ros)) %>% 
  gather(key = "Variable", value = "Value", P:roi)
  
  
#Simulations with combined model and ideal stocking and harvesting parameters identified above ###########
source('Combined_Model/epi_no_diag_prawn_mod.R')
par.aqua['muP'] <- par.aqua['muP']*4

## Set initial values and parameters ###########
years = 10   #number of years to simulate
t.all = c(0:(years*2*365)+366)  #total time vector

#Volenhovenii stocking and harvesting events ###########
nstart.vol = c(S1 = allvh.eqbm$S1, S2 = allvh.eqbm$S2, S3 = allvh.eqbm$S3, 
               E1 = allvh.eqbm$E1, E2 = allvh.eqbm$E2, E3 = allvh.eqbm$E3, 
               I1 = allvh.eqbm$I1, I2 = allvh.eqbm$I2, I3 = allvh.eqbm$I3, 
               Wt = allvh.eqbm$Wt, Wu = allvh.eqbm$Wu, 
               P = opt.vol$P_nought, L = opt.vol$L_nought) #Optimal stocking parameters from volenhovenii ROI optimization

  harvest.t.vol = opt.vol$h.t           #Optimal harvest time from volenhovenii optimization
  n.harvest.vol = floor(((years*365)+366)/harvest.t.vol)
  stocks.vol = data.frame(var = rep(c('P', 'L'), n.harvest.vol),
                          time = rep(366 + harvest.t.vol*c(0:(n.harvest.vol-1)), each = 2),
                          value = rep(c(nstart.vol['P'], nstart.vol['L']), n.harvest.vol),
                          method = rep('rep', n.harvest.vol*2))
    vol.harvests = stocks.vol[seq(1, nrow(stocks.vol), 2), 2]

  par.all.vol = c(par.aqua, par.snails,
                  a.s = 0.187178454,  # Allometric parameter for snail length-weight relationship, fitted to Sanna's data on B. glabrata
                  b.s = 2.536764792,  # Allometric parameter for snail length-weight relationship, fitted to Sanna's data on B. glabrata
                  ar.slp = 0.9050,    # Coefficient for relationship between biomass ratio and attack rate, fitted to data from Sokolow et al. 2014
                  #ar.int = 0.804928, # Coefficient for relationship between biomass ratio and attack rate, fitted to data from Sokolow et al. 2014
                  th = 0.38561)       # Coefficient for relationship between biomass ratio and handling time, fitted to data from Sokolow et al. 2014
  
#Rosenbergii stocking and harvesting events ###########
nstart.ros = c(S1 = allvh.eqbm$S1, S2 = allvh.eqbm$S2, S3 = allvh.eqbm$S3, 
               E1 = allvh.eqbm$E1, E2 = allvh.eqbm$E2, E3 = allvh.eqbm$E3, 
               I1 = allvh.eqbm$I1, I2 = allvh.eqbm$I2, I3 = allvh.eqbm$I3, 
               Wt = allvh.eqbm$Wt, Wu = allvh.eqbm$Wu, 
               P = opt.ros$P_nought, L = opt.ros$L_nought) #Optimal stocking parameters from volenhovenii ROI optimization

  harvest.t.ros = opt.ros$h.t
  n.harvest.ros = floor(((years*365)+366)/harvest.t.ros)
  stocks.ros = data.frame(var = rep(c('P', 'L'), n.harvest.ros),
                          time = rep(366 + harvest.t.ros*c(0:(n.harvest.ros-1)), each = 2),
                          value = rep(c(nstart.ros['P'], nstart.ros['L']), n.harvest.ros),
                          method = rep('rep', n.harvest.ros*2))
  ros.harvests = stocks.ros[seq(1, nrow(stocks.ros), 2), 2]
  
  par.all.ros = c(par.aqua, par.snails,
                  a.s = 0.187178454,  # Allometric parameter for snail length-weight relationship, fitted to Sanna's data on B. glabrata
                  b.s = 2.536764792,  # Allometric parameter for snail length-weight relationship, fitted to Sanna's data on B. glabrata
                  ar.slp = 0.9050,    # Coefficient for relationship between biomass ratio and attack rate, fitted to data from Sokolow et al. 2014
                  #ar.int = 0.804928, # Coefficient for relationship between biomass ratio and attack rate, fitted to data from Sokolow et al. 2014
                  th = 0.38561)       # Coefficient for relationship between biomass ratio and handling time, fitted to data from Sokolow et al. 2014
  
  par.all.ros['k'] = 0.0104333333  # alternate value for M. rosenbergii, from Sampaio & Valenti 1996: 0.0104333333
  

#allow for one year run in to display epi model at eqbm ###########
t.yr1 = c(0:365) 
nstart.yr1 = c(S1 = allvh.eqbm$S1, S2 = allvh.eqbm$S2, S3 = allvh.eqbm$S3, 
               E1 = allvh.eqbm$E1, E2 = allvh.eqbm$E2, E3 = allvh.eqbm$E3, 
               I1 = allvh.eqbm$I1, I2 = allvh.eqbm$I2, I3 = allvh.eqbm$I3, 
               Wt = allvh.eqbm$Wt, Wu = allvh.eqbm$Wu)

yr1 = as.data.frame(ode(nstart.yr1,t.yr1,snail_epi_allvh,par.snails))

  yr1$P = 0   #Add prawn variable to integrate with prawn stocking sims
  yr1$L = 0   #Add prawn variable to integrate with prawn stocking sims
  yr1$W = cov*yr1$Wt + (1-cov)*yr1$Wu
  yr1$prev = pnbinom(2, size = 0.2, mu = yr1$W, lower.tail = FALSE)   
  yr1$S.t = (yr1$S1 + yr1$S2 + yr1$S3) / area        # density susceptible snails
  yr1$E.t = (yr1$E1 + yr1$E2 + yr1$E3) / area        # density exposed snails 
  yr1$I.t = (yr1$I2 + yr1$I3 ) / area                # density infected snails
  yr1$N.t = (yr1$S.t + yr1$E.t + yr1$I.t)            # density snails
  yr1$t.1 = (yr1$S1 + yr1$E1) / area                    # density snails of size class 1
  yr1$t.2 = (yr1$S2 + yr1$E2 + yr1$I2) / area      # density snails of size class 2
  yr1$t.3 = (yr1$S3 + yr1$E3 + yr1$I3) / area      # density snails of size class 3

#Simulate annual MDA for n years ########
#mda events
  mdas = data.frame(var = rep('Wt', years),
                    time = 365*c(1:years)+1,
                    value = rep((1-cov*eff), years),
                    method = rep('multiply', years))
  
  sim.mda = as.data.frame(ode(nstart.yr1,t.all,snail_epi_allvh,par.snails,
                          events = list(data = mdas)))
  
  sim.mda$P = 0   #Add prawn variable to integrate with prawn stocking sims
  sim.mda$L = 0   #Add prawn variable to integrate with prawn stocking sims
  sim.mda$W = cov*sim.mda$Wt + (1-cov)*sim.mda$Wu
  sim.mda$prev = pnbinom(2, size = 0.2, mu = sim.mda$W, lower.tail = FALSE)   
  sim.mda$S.t = (sim.mda$S1 + sim.mda$S2 + sim.mda$S3) / area        # density susceptible snails
  sim.mda$E.t = (sim.mda$E1 + sim.mda$E2 + sim.mda$E3) / area        # density exposed snails 
  sim.mda$I.t = (sim.mda$I2 + sim.mda$I3 ) / area                    # density infected snails
  sim.mda$N.t = (sim.mda$S.t + sim.mda$E.t + sim.mda$I.t)            # density snails
  sim.mda$t.1 = (sim.mda$S1 + sim.mda$E1) / area                    # density snails of size class 1
  sim.mda$t.2 = (sim.mda$S2 + sim.mda$E2 + sim.mda$I2) / area      # density snails of size class 2
  sim.mda$t.3 = (sim.mda$S3 + sim.mda$E3 + sim.mda$I3) / area      # density snails of size class 3
  
  sim.mda = rbind(yr1, sim.mda)
    
#Simulate M. volenhovenii stocking for n years ########
sim.vol = as.data.frame(ode(nstart.vol,t.all,snail_prawn_model,par.all.vol,
                              events = list(data = stocks.vol)))
  
  sim.vol$W = cov*sim.vol$Wt + (1-cov)*sim.vol$Wu
  sim.vol$prev = pnbinom(2, size = 0.2, mu = sim.vol$W, lower.tail = FALSE)   
  sim.vol$S.t = (sim.vol$S1 + sim.vol$S2 + sim.vol$S3) / area        # density susceptible snails
  sim.vol$E.t = (sim.vol$E1 + sim.vol$E2 + sim.vol$E3) / area        # density exposed snails 
  sim.vol$I.t = (sim.vol$I2 + sim.vol$I3 ) / area                    # density infected snails
  sim.vol$N.t = (sim.vol$S.t + sim.vol$E.t + sim.vol$I.t)            # density snails
  sim.vol$t.1 = (sim.vol$S1 + sim.vol$E1) / area                          # density snails of size class 1
  sim.vol$t.2 = (sim.vol$S2 + sim.vol$E2 + sim.vol$I2) / area      # density snails of size class 2
  sim.vol$t.3 = (sim.vol$S3 + sim.vol$E3 + sim.vol$I3) / area      # density snails of size class 3
  
  sim.vol = rbind(yr1, sim.vol)
  
#Simulate M. rosenbergii stocking for n years ########
  sim.ros = as.data.frame(ode(nstart.ros,t.all,snail_prawn_model,par.all.ros,
                              events = list(data = stocks.ros)))
  
  sim.ros$W = cov*sim.ros$Wt + (1-cov)*sim.ros$Wu
  sim.ros$prev = pnbinom(2, size = 0.2, mu = sim.ros$W, lower.tail = FALSE)   
  sim.ros$S.t = (sim.ros$S1 + sim.ros$S2 + sim.ros$S3) / area        # density susceptible snails
  sim.ros$E.t = (sim.ros$E1 + sim.ros$E2 + sim.ros$E3) / area        # density exposed snails 
  sim.ros$I.t = (sim.ros$I2 + sim.ros$I3 ) / area                    # density infected snails
  sim.ros$N.t = (sim.ros$S.t + sim.ros$E.t + sim.ros$I.t)            # density snails
  sim.ros$t.1 = (sim.ros$S1 + sim.ros$E1) / area                          # density snails of size class 1
  sim.ros$t.2 = (sim.ros$S2 + sim.ros$E2 + sim.ros$I2) / area      # density snails of size class 2
  sim.ros$t.3 = (sim.ros$S3 + sim.ros$E3 + sim.ros$I3) / area      # density snails of size class 3
  
  sim.ros = rbind(yr1, sim.ros)

#Simulate annual mda along with volenhovenii stocking #############
mda.vol = rbind(mdas, stocks.vol)
  mda.vol = mda.vol[order(mda.vol$time),]
  
  sim.mda.vol = as.data.frame(ode(nstart.vol,t.all,snail_prawn_model,par.all.vol,
                              events = list(data = mda.vol)))
  
  sim.mda.vol$W = cov*sim.mda.vol$Wt + (1-cov)*sim.mda.vol$Wu
  sim.mda.vol$prev = pnbinom(2, size = 0.2, mu = sim.mda.vol$W, lower.tail = FALSE)   
  sim.mda.vol$S.t = (sim.mda.vol$S1 + sim.mda.vol$S2 + sim.mda.vol$S3) / area        # density susceptible snails
  sim.mda.vol$E.t = (sim.mda.vol$E1 + sim.mda.vol$E2 + sim.mda.vol$E3) / area        # density exposed snails 
  sim.mda.vol$I.t = (sim.mda.vol$I2 + sim.mda.vol$I3 ) / area                    # density infected snails
  sim.mda.vol$N.t = (sim.mda.vol$S.t + sim.mda.vol$E.t + sim.mda.vol$I.t)            # density snails
  sim.mda.vol$t.1 = (sim.mda.vol$S1 + sim.mda.vol$E1) / area                          # density snails of size class 1
  sim.mda.vol$t.2 = (sim.mda.vol$S2 + sim.mda.vol$E2 + sim.mda.vol$I2) / area      # density snails of size class 2
  sim.mda.vol$t.3 = (sim.mda.vol$S3 + sim.mda.vol$E3 + sim.mda.vol$I3) / area      # density snails of size class 3
  
  sim.mda.vol = rbind(yr1, sim.mda.vol)

#Simulate annual mda along with rosenbergii stocking #############
mda.ros = rbind(mdas, stocks.ros)
  mda.ros = mda.ros[order(mda.ros$time),]
  
  sim.mda.ros = as.data.frame(ode(nstart.ros,t.all,snail_prawn_model,par.all.ros,
                                  events = list(data = mda.ros)))
  
  sim.mda.ros$W = cov*sim.mda.ros$Wt + (1-cov)*sim.mda.ros$Wu
  sim.mda.ros$prev = pnbinom(2, size = 0.2, mu = sim.mda.ros$W, lower.tail = FALSE)   
  sim.mda.ros$S.t = (sim.mda.ros$S1 + sim.mda.ros$S2 + sim.mda.ros$S3) / area        # density susceptible snails
  sim.mda.ros$E.t = (sim.mda.ros$E1 + sim.mda.ros$E2 + sim.mda.ros$E3) / area        # density exposed snails 
  sim.mda.ros$I.t = (sim.mda.ros$I2 + sim.mda.ros$I3 ) / area                    # density infected snails
  sim.mda.ros$N.t = (sim.mda.ros$S.t + sim.mda.ros$E.t + sim.mda.ros$I.t)            # density snails
  sim.mda.ros$t.1 = (sim.mda.ros$S1 + sim.mda.ros$E1) / area                          # density snails of size class 1
  sim.mda.ros$t.2 = (sim.mda.ros$S2 + sim.mda.ros$E2 + sim.mda.ros$I2) / area      # density snails of size class 2
  sim.mda.ros$t.3 = (sim.mda.ros$S3 + sim.mda.ros$E3 + sim.mda.ros$I3) / area      # density snails of size class 3
  
  sim.mda.ros = rbind(yr1, sim.mda.ros)


  
  
#Save resulting simulations for reproducing figures #######
save.image(file = "Sensitivity_Analysis/Quadruple_mortality/quadruple_mortality_sims.RData")  
